apiVersion: v1
kind: Template
metadata:
  name: solace-xml-jms-soap-datagenerator
  annotations:
    description: Sample Spring Boot Application that demonstrate messaging with the Solace VMR - generators XML/SOAP/JMS Bank Transactions
    iconClass: icon-phalcon
    tags: 'instant-app,springboot,maven,java'
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-data-generator-jms-soap'
    spec:
      triggers:
        - type: ImageChange
          imageChange: {}
      source:
        type: Git
        git:
          uri: '${GIT_URI}'
          ref: '${GIT_REF}'
        contextDir: ''
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'jdk-us-app:latest'
#            name: 's2i-java:latest'
      output:
        to:
          kind: ImageStreamTag
          name: '${APPLICATION_NAME}-data-generator-jms-soap:latest'
      resources: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-data-generator-jms-soap'
    spec:
      dockerImageRepository: ''
      tags:
        - name: latest

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-data-generator-jms-soap'
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - '${APPLICATION_NAME}-data-generator-jms-soap'
            from:
              kind: ImageStreamTag
              name: '${APPLICATION_NAME}-data-generator-jms-soap:latest'
      replicas: 1
      selector:
        deploymentconfig: '${APPLICATION_NAME}-data-generator-jms-soap'
      template:
        metadata:
          labels:
            deploymentconfig: '${APPLICATION_NAME}-data-generator-jms-soap'
        spec:
          containers:
            - name: '${APPLICATION_NAME}-data-generator-jms-soap'
              image: '${APPLICATION_NAME}-data-generator-jms-soap'
              ports:
                - containerPort: 20010
                  protocol: TCP
              env:

              - name: 'SOL_RATE'
                value: '${SOL_RATE}'
              - name: 'SOL_TOPIC'
                value: '${SOL_TOPIC}' 
              - name: 'JAVA_OPTIONS'
                value: '-Djava.naming.provider.url=smf://${SOL_HOST} -DSolace_JMS_VPN=${SOL_VPN} -Djava.naming.security.principal=${SOL_USER} -Djava.naming.security.credentials=${SOL_PASSWORD}'

              resources: {}
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          dnsPolicy: ClusterFirst
          
parameters:
  - name: APPLICATION_NAME
    displayName: Application name
    description: The name for this Data Generator application.
    generate: expression
    from: '[A-Z0-9]{8}'
    value: bank-simulator-jms
    required: true
  - name: SOL_HOST
    description: The address for the Solace Messages Router -- do not append port to address
    value: test-cluster-svc.vmr-openshift-demo.svc:55555
    required: true
  - name: SOL_USER
    description: The client name for access to the Solace Message Broker
    value: 'heinz1'
    required: true
  - name: SOL_VPN
    description: 'The VPN namespace on the Solace Message Router'
    value: 'heinzvpn'
    required: true
  - name: SOL_PASSWORD
    description: The password for the Solace client
    value: 'heinz1'
    required: true
  - name: SOL_RATE
    description: The rate the generator is supposed to send messages is messages/second
    value: '1'
    required: false
  - name: SOL_TOPIC
    description: 'The topic to send messages, it can be the Queue Network Name'
    value: 'bank/data/xml'
    required: false

  - name: GIT_URI
    description: Git source URI for application
    value: 'https://github.com/hschaffner/solace_openshift_xml_jms_datagenerator'
  - name: GIT_REF
    description: Git branch/tag reference
    value: 'master'

 
labels:
  application: solace-springboot-messaging-sample
  createdBy: template-solace-springboot-messaging-sample
          
